### ISSUE TITLE
Jaco2 Installer Not Responding 

### ISSUE THREAD

**Issue by morison1** [Kinovarobotics/kinova_sdk_recompiled#1]
Hey I'm trying to run sdk_jaco2_1.4.0_install64 on Ubuntu 16.04,
but for some reason the installing is stuck at the following position:
https://imgur.com/a/Xi44Xct

I've tried this on two different computers but the issue persists. Is there a solution for this?

**Comment by samuelhovington** [comment]
Hi, is this issue actually solved? 

If not, you have to run the installer in sudo.
